import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { defineConfig, type Plugin, type ResolvedConfig } from "vite";

const require = createRequire(import.meta.url);

/** The Pyodide runtime files the browser needs; everything else in the package is node-only. */
const PYODIDE_ASSETS = [
  "pyodide.mjs",
  "pyodide.asm.mjs",
  "pyodide.asm.wasm",
  "python_stdlib.zip",
  "pyodide-lock.json",
];

/**
 * Copy the Pyodide runtime out of node_modules into `public/pyodide/`.
 *
 * The worker loads it from there at run time (see src/worker.ts), so nothing about Pyodide
 * goes through Vite's bundler - its `import("node:fs")` branches and its 9.6 MB .wasm are
 * both things a bundler handles badly. Self-hosting instead of using the CDN keeps the game
 * offline-first: after the first load everything comes from our own origin.
 */
function pyodideAssets(): Plugin {
  return {
    name: "los-pyodide-assets",
    buildStart() {
      const from = dirname(require.resolve("pyodide/package.json"));
      const to = join(import.meta.dirname, "public", "pyodide");
      mkdirSync(to, { recursive: true });
      for (const name of PYODIDE_ASSETS) {
        const src = join(from, name);
        const dest = join(to, name);
        if (existsSync(dest) && statSync(dest).size === statSync(src).size) continue;
        cpSync(src, dest);
      }
    },
  };
}

/** Files a service worker has no business precaching: itself, and its own manifest. */
const SW_EXCLUDED = new Set(["sw.js", "version.json"]);

function listOutputFiles(dir: string, prefix = ""): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (prefix === "" && SW_EXCLUDED.has(entry.name)) continue;
    const full = join(dir, entry.name);
    const rel = prefix + entry.name;
    if (entry.isDirectory()) out.push(...listOutputFiles(full, `${rel}/`));
    else out.push(rel);
  }
  return out;
}

/**
 * Hashes what will actually be served: for every precached file, its path *and* its bytes.
 *
 * Hashing the file list alone (what this used to do) misses every change that keeps the same
 * names - `engine.zip`, `index.html`, `404.html` and the Pyodide runtime are all unhashed
 * paths in `public/`, so an engine edit produced a byte-different build under an identical
 * cache name and returning players kept the stale copy forever. The name part stays in the
 * digest so a pure rename still rolls the cache.
 */
function precacheVersion(outDir: string, files: string[]): string {
  const digest = createHash("sha1");
  for (const rel of files) {
    // The path, its byte length and its bytes: no two different builds can collide by
    // running one file's content into the next one's name.
    const bytes = readFileSync(join(outDir, rel));
    digest.update(`${rel}:${bytes.length};`);
    digest.update(bytes);
  }
  return digest.digest("hex").slice(0, 12);
}

/**
 * Hand-written offline cache (docs/plans/web_version_plan.md W5 - no plugin): after `vite build` writes
 * `dist/`, this walks the finished output (Vite's hashed JS/CSS, `engine.zip`, the Pyodide
 * runtime, index.html) and writes `dist/version.json` plus `dist/sw.js`, a cache-first service
 * worker whose cache name embeds a hash of those files' names *and contents*, so any changed
 * build gets a fresh cache and the old one is dropped on activate. It never touches saves -
 * those live in localStorage, not behind any URL a service worker could intercept.
 */
function serviceWorker(): Plugin {
  let config: ResolvedConfig;
  return {
    name: "los-service-worker",
    apply: "build",
    configResolved(resolved) {
      config = resolved;
    },
    closeBundle() {
      const outDir = join(import.meta.dirname, config.build.outDir);
      if (!existsSync(outDir)) return;
      const files = listOutputFiles(outDir).sort();
      const version = precacheVersion(outDir, files);

      writeFileSync(
        join(outDir, "version.json"),
        JSON.stringify({ version, builtAt: new Date().toISOString() }, null, 2),
      );

      const precache = JSON.stringify(files, null, 2);
      const swSource = `// Generated by vite.config.ts (los-service-worker) at build time - do not hand-edit.
// Cache-first for the precached files below; everything else passes straight to the network.
// Saves are never here: the game keeps them in localStorage, not behind a fetchable URL.
const CACHE_NAME = "los-cache-${version}";
const PRECACHE = ${precache};

function scopePath() {
  return new URL(self.registration.scope).pathname;
}

function relativePath(url) {
  const scope = scopePath();
  const path = url.pathname.startsWith(scope) ? url.pathname.slice(scope.length) : url.pathname;
  return path === "" ? "index.html" : path;
}

/** True for a request for the app document itself, under either of the two URLs it answers to. */
function isAppDocument(request, url) {
  if (request.mode !== "navigate") return false;
  const scope = scopePath();
  return url.pathname === scope || url.pathname === scope + "index.html";
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) =>
        // "./" is the scope root itself: the URL a player actually has bookmarked. It serves
        // the same bytes as index.html but is a separate cache entry, so precache both or an
        // offline reload of the bare directory URL finds nothing.
        Promise.all(["./", ...PRECACHE].map((path) => cache.add(path).catch(() => {}))),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("los-cache-") && key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // A navigation carries the browser's own headers and cache mode, so \`cache.match(request)\`
  // can miss the entry install() put there under a plain URL - and a reload of the bare
  // directory URL would then fall through to the network and fail offline. Normalise every
  // navigation to the app to the same two cache keys, whichever URL form it arrived as.
  if (isAppDocument(request, url)) {
    const scope = scopePath();
    event.respondWith(
      caches.open(CACHE_NAME).then(async (cache) => {
        const cached = (await cache.match(scope)) || (await cache.match(scope + "index.html"));
        if (cached) return cached;
        const response = await fetch(request);
        if (response.ok) cache.put(scope, response.clone());
        return response;
      }),
    );
    return;
  }

  if (!PRECACHE.includes(relativePath(url))) return;

  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      const cached = await cache.match(request);
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok) cache.put(request, response.clone());
      return response;
    }),
  );
});
`;
      writeFileSync(join(outDir, "sw.js"), swSource);
      console.log(`dist/sw.js: cache "los-cache-${version}", ${files.length} files precached`);
    },
  };
}

// GitHub Pages serves this project under /legacy-of-stars-2/, not the domain root; the workflow
// (.github/workflows/web.yml) sets VITE_BASE accordingly. Local dev/preview default to "/".
// Everything that reaches the Pyodide runtime or engine.zip resolves against
// `import.meta.env.BASE_URL` (bridge.ts / worker.ts), so this one setting is enough.
const base = process.env["VITE_BASE"] || "/";

export default defineConfig({
  base,
  plugins: [pyodideAssets(), serviceWorker()],
  build: {
    target: "es2022",
    // engine.zip and the Pyodide runtime are served as-is from public/, never inlined.
    assetsInlineLimit: 0,
  },
  worker: { format: "es" },
  server: { headers: { "Cache-Control": "no-store" } },
});
